#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment_1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Employee_Management")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee_Detail(Employee_Detail instance);
    partial void UpdateEmployee_Detail(Employee_Detail instance);
    partial void DeleteEmployee_Detail(Employee_Detail instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Assessment_1.Properties.Settings.Default.Employee_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee_Detail> Employee_Details
		{
			get
			{
				return this.GetTable<Employee_Detail>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Add_Emp_Details")]
		public int Add_Emp_Details([global::System.Data.Linq.Mapping.ParameterAttribute(Name="E_Name", DbType="VarChar(50)")] string e_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="E_Sal", DbType="Decimal(10,2)")] System.Nullable<decimal> e_Sal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="E_Type", DbType="Char(1)")] System.Nullable<char> e_Type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), e_Name, e_Sal, e_Type);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee_Details")]
	public partial class Employee_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_No;
		
		private string _Emp_Name;
		
		private System.Nullable<decimal> _Emp_Sal;
		
		private System.Nullable<char> _Emp_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_NoChanging(int value);
    partial void OnEmp_NoChanged();
    partial void OnEmp_NameChanging(string value);
    partial void OnEmp_NameChanged();
    partial void OnEmp_SalChanging(System.Nullable<decimal> value);
    partial void OnEmp_SalChanged();
    partial void OnEmp_TypeChanging(System.Nullable<char> value);
    partial void OnEmp_TypeChanged();
    #endregion
		
		public Employee_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Emp_No
		{
			get
			{
				return this._Emp_No;
			}
			set
			{
				if ((this._Emp_No != value))
				{
					this.OnEmp_NoChanging(value);
					this.SendPropertyChanging();
					this._Emp_No = value;
					this.SendPropertyChanged("Emp_No");
					this.OnEmp_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Emp_Name
		{
			get
			{
				return this._Emp_Name;
			}
			set
			{
				if ((this._Emp_Name != value))
				{
					this.OnEmp_NameChanging(value);
					this.SendPropertyChanging();
					this._Emp_Name = value;
					this.SendPropertyChanged("Emp_Name");
					this.OnEmp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Sal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Emp_Sal
		{
			get
			{
				return this._Emp_Sal;
			}
			set
			{
				if ((this._Emp_Sal != value))
				{
					this.OnEmp_SalChanging(value);
					this.SendPropertyChanging();
					this._Emp_Sal = value;
					this.SendPropertyChanged("Emp_Sal");
					this.OnEmp_SalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Type", DbType="Char(1)")]
		public System.Nullable<char> Emp_Type
		{
			get
			{
				return this._Emp_Type;
			}
			set
			{
				if ((this._Emp_Type != value))
				{
					this.OnEmp_TypeChanging(value);
					this.SendPropertyChanging();
					this._Emp_Type = value;
					this.SendPropertyChanged("Emp_Type");
					this.OnEmp_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
